"""
========================================================================
 База данных менеджера ботов.
------------------------------------------------------------------------
 Один и тот же синхронный API работает на двух бэкендах:

   • PostgreSQL / Neon — если задан DATABASE_URL (через psycopg 3);
   • SQLite           — иначе (локальный файл, для разработки).

 Это позволяет деплоить на Railway с Neon-базой, не меняя handler'ы.
 SQL пишется с плейсхолдерами «?», а для Postgres они переводятся в «%s».
========================================================================
"""

from __future__ import annotations

import os
import secrets
import threading
import time
from typing import Any

from config import DB_PATH

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

_lock = threading.Lock()


# ----------------------------------------------------------------- бэкенд
class _DB:
    """Тонкая обёртка над psycopg/sqlite с единым интерфейсом."""

    def __init__(self) -> None:
        if DATABASE_URL:
            import psycopg
            from psycopg.rows import dict_row

            self.kind = "pg"
            self.conn = psycopg.connect(
                DATABASE_URL, autocommit=True, row_factory=dict_row
            )
        else:
            import sqlite3

            self.kind = "sqlite"
            self.conn = sqlite3.connect(DB_PATH, check_same_thread=False)
            self.conn.row_factory = sqlite3.Row

    def _q(self, sql: str) -> str:
        return sql.replace("?", "%s") if self.kind == "pg" else sql

    def execute(self, sql: str, params: tuple = ()):  # noqa: ANN001
        cur = self.conn.cursor()
        cur.execute(self._q(sql), params)
        return cur

    def commit(self) -> None:
        # для PG с autocommit=True это no-op, для sqlite — реальный commit
        try:
            self.conn.commit()
        except Exception:
            pass

    def one(self, sql: str, params: tuple = ()) -> dict | None:
        cur = self.execute(sql, params)
        row = cur.fetchone()
        return dict(row) if row is not None else None

    def all(self, sql: str, params: tuple = ()) -> list[dict]:
        cur = self.execute(sql, params)
        return [dict(r) for r in cur.fetchall()]


_db = _DB()


def _now() -> int:
    return int(time.time())


# ------------------------------------------------------------------ схема
def init_db() -> None:
    """Создаёт таблицы, если их нет. Зовётся один раз при старте."""
    auto_pk = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if _db.kind == "pg"
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    ddl = [
        """
        CREATE TABLE IF NOT EXISTS users (
            id         BIGINT PRIMARY KEY,
            username   TEXT,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS folders (
            id         {auto_pk},
            owner_id   BIGINT NOT NULL,
            name       TEXT NOT NULL,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS bots (
            id              {auto_pk},
            owner_id        BIGINT NOT NULL,
            token           TEXT UNIQUE NOT NULL,
            username        TEXT,
            tg_id           BIGINT,
            enabled         INTEGER NOT NULL DEFAULT 1,
            auto_approve    INTEGER NOT NULL DEFAULT 1,
            welcome_message TEXT,
            folder_id       BIGINT,
            template        TEXT NOT NULL DEFAULT 'standard',
            guard_enabled   INTEGER NOT NULL DEFAULT 0,
            user_secret     TEXT,
            miniapp_enabled INTEGER NOT NULL DEFAULT 0,
            created_at      BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS launches (
            id         {auto_pk},
            bot_tg_id  BIGINT NOT NULL,
            user_id    BIGINT NOT NULL,
            username   TEXT,
            geo        TEXT,
            created_at BIGINT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS direct_link_bots (
            bot_id         BIGINT PRIMARY KEY,
            enabled        INTEGER NOT NULL DEFAULT 0,
            startapp_token TEXT NOT NULL,
            token_version  INTEGER NOT NULL DEFAULT 1,
            created_at     BIGINT NOT NULL,
            updated_at     BIGINT NOT NULL
        )
        """,
    ]
    with _lock:
        for stmt in ddl:
            _db.execute(stmt)
        _db.commit()


# ----------------------------------------------------------------- users
def add_user(user_id: int, username: str | None) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO users(id, username, created_at) VALUES(?,?,?) "
            "ON CONFLICT(id) DO UPDATE SET username=excluded.username",
            (user_id, username, _now()),
        )
        _db.commit()


# --------------------------------------------------------------- folders
def add_folder(owner_id: int, name: str) -> int:
    with _lock:
        row = _db.one(
            "INSERT INTO folders(owner_id, name, created_at) VALUES(?,?,?) "
            "RETURNING id",
            (owner_id, name, _now()),
        )
        _db.commit()
    return int(row["id"])


def get_folders(owner_id: int) -> list[dict]:
    with _lock:
        return _db.all(
            "SELECT * FROM folders WHERE owner_id=? ORDER BY id", (owner_id,)
        )


def get_folder(folder_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM folders WHERE id=?", (folder_id,))


def delete_folder(folder_id: int) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET folder_id=NULL WHERE folder_id=?", (folder_id,)
        )
        _db.execute("DELETE FROM folders WHERE id=?", (folder_id,))
        _db.commit()


# ------------------------------------------------------------------ bots
def token_exists(token: str) -> bool:
    with _lock:
        return _db.one("SELECT 1 AS x FROM bots WHERE token=?", (token,)) is not None


def add_bot(
    owner_id: int,
    token: str,
    username: str,
    tg_id: int | None = None,
) -> int:
    user_secret = secrets.token_urlsafe(6)
    with _lock:
        row = _db.one(
            "INSERT INTO bots(owner_id, token, username, tg_id, user_secret, "
            "created_at) VALUES(?,?,?,?,?,?) RETURNING id",
            (owner_id, token, username, tg_id, user_secret, _now()),
        )
        _db.commit()
    return int(row["id"])


def get_bot(bot_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM bots WHERE id=?", (bot_id,))


def get_bot_by_tg_id(tg_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM bots WHERE tg_id=?", (tg_id,))


def get_user_bots(owner_id: int, folder_id: int | None = None) -> list[dict]:
    with _lock:
        if folder_id is None:
            return _db.all(
                "SELECT * FROM bots WHERE owner_id=? ORDER BY id", (owner_id,)
            )
        return _db.all(
            "SELECT * FROM bots WHERE owner_id=? AND folder_id=? ORDER BY id",
            (owner_id, folder_id),
        )


def get_all_bots() -> list[dict]:
    with _lock:
        return _db.all("SELECT * FROM bots ORDER BY id")


def update_bot_field(bot_id: int, field: str, value: Any) -> None:
    allowed = {
        "enabled",
        "auto_approve",
        "welcome_message",
        "folder_id",
        "template",
        "guard_enabled",
        "user_secret",
        "username",
        "miniapp_enabled",
    }
    if field not in allowed:
        raise ValueError(f"Поле {field!r} нельзя обновлять")
    with _lock:
        _db.execute(f"UPDATE bots SET {field}=? WHERE id=?", (value, bot_id))
        _db.commit()


def delete_bot(bot_id: int) -> None:
    with _lock:
        row = _db.one("SELECT tg_id FROM bots WHERE id=?", (bot_id,))
        _db.execute("DELETE FROM bots WHERE id=?", (bot_id,))
        if row and row.get("tg_id") is not None:
            _db.execute(
                "DELETE FROM direct_link_bots WHERE bot_id=?", (row["tg_id"],)
            )
        _db.commit()


# -------------------------------------------------------------- launches
def record_launch(
    bot_tg_id: int, user_id: int, username: str | None, geo: str | None
) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO launches(bot_tg_id, user_id, username, geo, created_at) "
            "VALUES(?,?,?,?,?)",
            (bot_tg_id, user_id, username, geo, _now()),
        )
        _db.commit()


def get_launch_stats(bot_tg_id: int) -> dict:
    with _lock:
        total = _db.one(
            "SELECT COUNT(*) AS c FROM launches WHERE bot_tg_id=?", (bot_tg_id,)
        )["c"]
        unique = _db.one(
            "SELECT COUNT(DISTINCT user_id) AS c FROM launches WHERE bot_tg_id=?",
            (bot_tg_id,),
        )["c"]
        geo_rows = _db.all(
            "SELECT COALESCE(geo,'—') AS geo, COUNT(*) AS c FROM launches "
            "WHERE bot_tg_id=? GROUP BY geo ORDER BY c DESC LIMIT 10",
            (bot_tg_id,),
        )
    return {
        "total": total,
        "unique": unique,
        "by_geo": [(r["geo"], r["c"]) for r in geo_rows],
    }


def get_recent_launches(bot_tg_id: int, limit: int = 15) -> list[dict]:
    with _lock:
        return _db.all(
            "SELECT user_id, username, geo, created_at FROM launches "
            "WHERE bot_tg_id=? ORDER BY id DESC LIMIT ?",
            (bot_tg_id, limit),
        )


def direct_link_enabled(bot_tg_id: int | None) -> bool:
    if not bot_tg_id:
        return False
    with _lock:
        row = _db.one(
            "SELECT enabled FROM direct_link_bots WHERE bot_id=?", (bot_tg_id,)
        )
    return bool(row and row["enabled"])


def get_bot_user_ids(bot_tg_id: int) -> list[int]:
    with _lock:
        rows = _db.all(
            "SELECT DISTINCT user_id FROM launches WHERE bot_tg_id=?", (bot_tg_id,)
        )
    return [r["user_id"] for r in rows]


# --------------------------------------- хранилище модуля «Прямая ссылка»
def dl_get(bot_id: int) -> dict | None:
    with _lock:
        row = _db.one(
            "SELECT enabled, startapp_token, token_version "
            "FROM direct_link_bots WHERE bot_id=?",
            (bot_id,),
        )
    if row is None:
        return None
    return {
        "enabled": bool(row["enabled"]),
        "startapp_token": row["startapp_token"],
        "token_version": row["token_version"],
    }


def dl_init(bot_id: int, startapp_token: str) -> dict:
    now = _now()
    with _lock:
        _db.execute(
            "INSERT INTO direct_link_bots(bot_id, enabled, startapp_token, "
            "token_version, created_at, updated_at) VALUES(?,0,?,1,?,?) "
            "ON CONFLICT(bot_id) DO NOTHING",
            (bot_id, startapp_token, now, now),
        )
        _db.commit()
    state = dl_get(bot_id)
    assert state is not None
    return state


def dl_set_enabled(bot_id: int, enabled: bool) -> None:
    with _lock:
        _db.execute(
            "UPDATE direct_link_bots SET enabled=?, updated_at=? WHERE bot_id=?",
            (1 if enabled else 0, _now(), bot_id),
        )
        _db.commit()


def dl_rotate(bot_id: int, new_token: str) -> dict:
    with _lock:
        _db.execute(
            "UPDATE direct_link_bots SET startapp_token=?, "
            "token_version=token_version+1, updated_at=? WHERE bot_id=?",
            (new_token, _now(), bot_id),
        )
        _db.commit()
    state = dl_get(bot_id)
    assert state is not None
    return state
