"""
========================================================================
 База данных менеджера ботов.
------------------------------------------------------------------------
 Один и тот же синхронный API работает на двух бэкендах:

   • PostgreSQL / Neon — если задан DATABASE_URL (через psycopg 3);
   • SQLite           — иначе (локальный файл, для разработки).

 Это позволяет деплоить на Railway с Neon-базой, не меняя handler'ы.
 SQL пишется с плейсхолдерами «?», а для Postgres они переводятся в «%s».
========================================================================
"""

from __future__ import annotations

import json
import os
import secrets
import threading
import time
from typing import Any

from config import DB_PATH

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

_lock = threading.Lock()


# ----------------------------------------------------------------- бэкенд
class _DB:
    """Тонкая обёртка над psycopg/sqlite с единым интерфейсом.

    Соединение умеет восстанавливаться: serverless-Postgres (Neon) закрывает
    простаивающие коннекты, поэтому при ошибке соединения переподключаемся и
    повторяем запрос один раз.
    """

    def __init__(self) -> None:
        self._connect()

    def _connect(self) -> None:
        if DATABASE_URL:
            import psycopg
            from psycopg.rows import dict_row

            self.kind = "pg"
            self._conn_errors: tuple[type[Exception], ...] = (
                psycopg.OperationalError,
                psycopg.InterfaceError,
            )
            self.conn = psycopg.connect(
                DATABASE_URL,
                autocommit=True,
                row_factory=dict_row,
                # держим соединение живым, чтобы реже ловить простой-таймаут
                keepalives=1,
                keepalives_idle=30,
                keepalives_interval=10,
                keepalives_count=5,
            )
        else:
            import sqlite3

            self.kind = "sqlite"
            self._conn_errors = (sqlite3.OperationalError, sqlite3.ProgrammingError)
            self.conn = sqlite3.connect(DB_PATH, check_same_thread=False)
            self.conn.row_factory = sqlite3.Row

    def _q(self, sql: str) -> str:
        return sql.replace("?", "%s") if self.kind == "pg" else sql

    def execute(self, sql: str, params: tuple = ()):  # noqa: ANN001
        try:
            cur = self.conn.cursor()
            cur.execute(self._q(sql), params)
            return cur
        except self._conn_errors:
            # соединение оборвалось — переподключаемся и повторяем один раз
            self._connect()
            cur = self.conn.cursor()
            cur.execute(self._q(sql), params)
            return cur

    def commit(self) -> None:
        # для PG с autocommit=True это no-op, для sqlite — реальный commit
        try:
            self.conn.commit()
        except Exception:
            pass

    def one(self, sql: str, params: tuple = ()) -> dict | None:
        cur = self.execute(sql, params)
        row = cur.fetchone()
        return dict(row) if row is not None else None

    def all(self, sql: str, params: tuple = ()) -> list[dict]:
        cur = self.execute(sql, params)
        return [dict(r) for r in cur.fetchall()]


_db = _DB()


def _now() -> int:
    return int(time.time())


# ------------------------------------------------------------------ схема
def init_db() -> None:
    """Создаёт таблицы, если их нет. Зовётся один раз при старте."""
    auto_pk = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if _db.kind == "pg"
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    ddl = [
        """
        CREATE TABLE IF NOT EXISTS users (
            id         BIGINT PRIMARY KEY,
            username   TEXT,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS folders (
            id         {auto_pk},
            owner_id   BIGINT NOT NULL,
            name       TEXT NOT NULL,
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS bots (
            id              {auto_pk},
            owner_id        BIGINT NOT NULL,
            token           TEXT UNIQUE NOT NULL,
            username        TEXT,
            tg_id           BIGINT,
            enabled         INTEGER NOT NULL DEFAULT 1,
            auto_approve    INTEGER NOT NULL DEFAULT 1,
            welcome_message TEXT,
            folder_id       BIGINT,
            template        TEXT NOT NULL DEFAULT 'standard',
            guard_enabled   INTEGER NOT NULL DEFAULT 0,
            user_secret     TEXT,
            miniapp_enabled INTEGER NOT NULL DEFAULT 0,
            created_at      BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS launches (
            id         {auto_pk},
            bot_tg_id  BIGINT NOT NULL,
            user_id    BIGINT NOT NULL,
            username   TEXT,
            geo        TEXT,
            created_at BIGINT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS direct_link_bots (
            bot_id         BIGINT PRIMARY KEY,
            enabled        INTEGER NOT NULL DEFAULT 0,
            startapp_token TEXT NOT NULL,
            token_version  INTEGER NOT NULL DEFAULT 1,
            created_at     BIGINT NOT NULL,
            updated_at     BIGINT NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS templates (
            id         {auto_pk},
            owner_id   BIGINT NOT NULL,
            name       TEXT NOT NULL,
            kind       TEXT NOT NULL DEFAULT 'standard',
            share_code TEXT,
            content    TEXT NOT NULL DEFAULT '{{}}',
            created_at BIGINT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS proxies (
            id         {auto_pk},
            owner_id   BIGINT NOT NULL,
            url        TEXT NOT NULL,
            label      TEXT,
            created_at BIGINT
        )
        """,
    ]
    with _lock:
        for stmt in ddl:
            _db.execute(stmt)
        # миграции: новые колонки к уже существующим таблицам
        if not _column_exists("bots", "template_id"):
            _db.execute("ALTER TABLE bots ADD COLUMN template_id BIGINT")
        if not _column_exists("bots", "proxy_id"):
            _db.execute("ALTER TABLE bots ADD COLUMN proxy_id BIGINT")
        _db.commit()


def _column_exists(table: str, column: str) -> bool:
    """Есть ли колонка (для аккуратных миграций без падений на проде)."""
    if _db.kind == "pg":
        row = _db.one(
            "SELECT 1 AS x FROM information_schema.columns "
            "WHERE table_name=? AND column_name=?",
            (table, column),
        )
        return row is not None
    rows = _db.all(f"PRAGMA table_info({table})")
    return any(r["name"] == column for r in rows)


# ----------------------------------------------------------------- users
def add_user(user_id: int, username: str | None) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO users(id, username, created_at) VALUES(?,?,?) "
            "ON CONFLICT(id) DO UPDATE SET username=excluded.username",
            (user_id, username, _now()),
        )
        _db.commit()


# --------------------------------------------------------------- folders
def add_folder(owner_id: int, name: str) -> int:
    with _lock:
        row = _db.one(
            "INSERT INTO folders(owner_id, name, created_at) VALUES(?,?,?) "
            "RETURNING id",
            (owner_id, name, _now()),
        )
        _db.commit()
    return int(row["id"])


def get_folders(owner_id: int) -> list[dict]:
    with _lock:
        return _db.all(
            "SELECT * FROM folders WHERE owner_id=? ORDER BY id", (owner_id,)
        )


def get_folder(folder_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM folders WHERE id=?", (folder_id,))


def delete_folder(folder_id: int) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET folder_id=NULL WHERE folder_id=?", (folder_id,)
        )
        _db.execute("DELETE FROM folders WHERE id=?", (folder_id,))
        _db.commit()


# ------------------------------------------------------------------ bots
def token_exists(token: str) -> bool:
    with _lock:
        return _db.one("SELECT 1 AS x FROM bots WHERE token=?", (token,)) is not None


def add_bot(
    owner_id: int,
    token: str,
    username: str,
    tg_id: int | None = None,
) -> int:
    user_secret = secrets.token_urlsafe(6)
    with _lock:
        row = _db.one(
            "INSERT INTO bots(owner_id, token, username, tg_id, user_secret, "
            "created_at) VALUES(?,?,?,?,?,?) RETURNING id",
            (owner_id, token, username, tg_id, user_secret, _now()),
        )
        _db.commit()
    return int(row["id"])


def get_bot(bot_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM bots WHERE id=?", (bot_id,))


def get_bot_by_tg_id(tg_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM bots WHERE tg_id=?", (tg_id,))


def get_user_bots(owner_id: int, folder_id: int | None = None) -> list[dict]:
    with _lock:
        if folder_id is None:
            return _db.all(
                "SELECT * FROM bots WHERE owner_id=? ORDER BY id", (owner_id,)
            )
        return _db.all(
            "SELECT * FROM bots WHERE owner_id=? AND folder_id=? ORDER BY id",
            (owner_id, folder_id),
        )


def get_all_bots() -> list[dict]:
    with _lock:
        return _db.all("SELECT * FROM bots ORDER BY id")


def update_bot_field(bot_id: int, field: str, value: Any) -> None:
    allowed = {
        "enabled",
        "auto_approve",
        "welcome_message",
        "folder_id",
        "template",
        "guard_enabled",
        "user_secret",
        "username",
        "miniapp_enabled",
    }
    if field not in allowed:
        raise ValueError(f"Поле {field!r} нельзя обновлять")
    with _lock:
        _db.execute(f"UPDATE bots SET {field}=? WHERE id=?", (value, bot_id))
        _db.commit()


def delete_bot(bot_id: int) -> None:
    with _lock:
        row = _db.one("SELECT tg_id FROM bots WHERE id=?", (bot_id,))
        _db.execute("DELETE FROM bots WHERE id=?", (bot_id,))
        if row and row.get("tg_id") is not None:
            _db.execute(
                "DELETE FROM direct_link_bots WHERE bot_id=?", (row["tg_id"],)
            )
        _db.commit()


def set_bot_template(bot_id: int, template_id: int | None) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET template_id=? WHERE id=?", (template_id, bot_id)
        )
        _db.commit()


# ----------------------------------------------------------------- templates
# Шаблоны принадлежат владельцу (owner_id) и общие для всех его ботов:
# созданный в одном боте шаблон доступен в любом другом. Поля редактора
# хранятся в JSON-блоке content, чтобы расширять набор без миграций.


def _hydrate_template(t: dict | None) -> dict | None:
    if t is None:
        return None
    try:
        t["content"] = json.loads(t.get("content") or "{}")
    except (ValueError, TypeError):
        t["content"] = {}
    return t


def create_template(
    owner_id: int,
    name: str,
    kind: str = "standard",
    content: dict | None = None,
) -> int:
    with _lock:
        row = _db.one(
            "INSERT INTO templates(owner_id, name, kind, content, created_at) "
            "VALUES(?,?,?,?,?) RETURNING id",
            (owner_id, name, kind, json.dumps(content or {}, ensure_ascii=False), _now()),
        )
        _db.commit()
    return int(row["id"])


def get_template(template_id: int) -> dict | None:
    with _lock:
        return _hydrate_template(
            _db.one("SELECT * FROM templates WHERE id=?", (template_id,))
        )


def get_owner_templates(owner_id: int) -> list[dict]:
    with _lock:
        rows = _db.all(
            "SELECT * FROM templates WHERE owner_id=? ORDER BY id", (owner_id,)
        )
    return [_hydrate_template(r) for r in rows]


def update_template_content(template_id: int, key: str, value: Any) -> None:
    """Записать одно поле редактора в JSON-content шаблона."""
    with _lock:
        row = _db.one("SELECT content FROM templates WHERE id=?", (template_id,))
        if row is None:
            return
        try:
            content = json.loads(row.get("content") or "{}")
        except (ValueError, TypeError):
            content = {}
        content[key] = value
        _db.execute(
            "UPDATE templates SET content=? WHERE id=?",
            (json.dumps(content, ensure_ascii=False), template_id),
        )
        _db.commit()


def rename_template(template_id: int, name: str) -> None:
    with _lock:
        _db.execute(
            "UPDATE templates SET name=? WHERE id=?", (name, template_id)
        )
        _db.commit()


def delete_template(template_id: int) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET template_id=NULL WHERE template_id=?", (template_id,)
        )
        _db.execute("DELETE FROM templates WHERE id=?", (template_id,))
        _db.commit()


def copy_template(template_id: int) -> int | None:
    t = get_template(template_id)
    if t is None:
        return None
    return create_template(
        t["owner_id"], f"{t['name']} (копия)", t["kind"], t["content"]
    )


def set_template_share_code(template_id: int, code: str) -> None:
    with _lock:
        _db.execute(
            "UPDATE templates SET share_code=? WHERE id=?", (code, template_id)
        )
        _db.commit()


def get_template_by_share_code(code: str) -> dict | None:
    with _lock:
        return _hydrate_template(
            _db.one("SELECT * FROM templates WHERE share_code=?", (code,))
        )


# ----------------------------------------------------------------- proxies
# Пул прокси владельца (общий для всех его ботов). Бот ссылается на выбранный
# прокси через bots.proxy_id; через него поднимается polling дочернего бота.


def add_proxy(owner_id: int, url: str, label: str | None = None) -> int:
    with _lock:
        row = _db.one(
            "INSERT INTO proxies(owner_id, url, label, created_at) "
            "VALUES(?,?,?,?) RETURNING id",
            (owner_id, url, label, _now()),
        )
        _db.commit()
    return int(row["id"])


def get_owner_proxies(owner_id: int) -> list[dict]:
    with _lock:
        return _db.all(
            "SELECT * FROM proxies WHERE owner_id=? ORDER BY id", (owner_id,)
        )


def get_proxy(proxy_id: int) -> dict | None:
    with _lock:
        return _db.one("SELECT * FROM proxies WHERE id=?", (proxy_id,))


def delete_proxy(proxy_id: int) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET proxy_id=NULL WHERE proxy_id=?", (proxy_id,)
        )
        _db.execute("DELETE FROM proxies WHERE id=?", (proxy_id,))
        _db.commit()


def set_bot_proxy(bot_id: int, proxy_id: int | None) -> None:
    with _lock:
        _db.execute(
            "UPDATE bots SET proxy_id=? WHERE id=?", (proxy_id, bot_id)
        )
        _db.commit()


# -------------------------------------------------------------- launches
def record_launch(
    bot_tg_id: int, user_id: int, username: str | None, geo: str | None
) -> None:
    with _lock:
        _db.execute(
            "INSERT INTO launches(bot_tg_id, user_id, username, geo, created_at) "
            "VALUES(?,?,?,?,?)",
            (bot_tg_id, user_id, username, geo, _now()),
        )
        _db.commit()


def get_launch_stats(bot_tg_id: int) -> dict:
    with _lock:
        total = _db.one(
            "SELECT COUNT(*) AS c FROM launches WHERE bot_tg_id=?", (bot_tg_id,)
        )["c"]
        unique = _db.one(
            "SELECT COUNT(DISTINCT user_id) AS c FROM launches WHERE bot_tg_id=?",
            (bot_tg_id,),
        )["c"]
        geo_rows = _db.all(
            "SELECT COALESCE(geo,'—') AS geo, COUNT(*) AS c FROM launches "
            "WHERE bot_tg_id=? GROUP BY geo ORDER BY c DESC LIMIT 10",
            (bot_tg_id,),
        )
    return {
        "total": total,
        "unique": unique,
        "by_geo": [(r["geo"], r["c"]) for r in geo_rows],
    }


def get_recent_launches(bot_tg_id: int, limit: int = 15) -> list[dict]:
    with _lock:
        return _db.all(
            "SELECT user_id, username, geo, created_at FROM launches "
            "WHERE bot_tg_id=? ORDER BY id DESC LIMIT ?",
            (bot_tg_id, limit),
        )


def direct_link_enabled(bot_tg_id: int | None) -> bool:
    if not bot_tg_id:
        return False
    with _lock:
        row = _db.one(
            "SELECT enabled FROM direct_link_bots WHERE bot_id=?", (bot_tg_id,)
        )
    return bool(row and row["enabled"])


def get_bot_user_ids(bot_tg_id: int) -> list[int]:
    with _lock:
        rows = _db.all(
            "SELECT DISTINCT user_id FROM launches WHERE bot_tg_id=?", (bot_tg_id,)
        )
    return [r["user_id"] for r in rows]


# --------------------------------------- хранилище модуля «Прямая ссылка»
def dl_get(bot_id: int) -> dict | None:
    with _lock:
        row = _db.one(
            "SELECT enabled, startapp_token, token_version "
            "FROM direct_link_bots WHERE bot_id=?",
            (bot_id,),
        )
    if row is None:
        return None
    return {
        "enabled": bool(row["enabled"]),
        "startapp_token": row["startapp_token"],
        "token_version": row["token_version"],
    }


def dl_init(bot_id: int, startapp_token: str) -> dict:
    now = _now()
    with _lock:
        _db.execute(
            "INSERT INTO direct_link_bots(bot_id, enabled, startapp_token, "
            "token_version, created_at, updated_at) VALUES(?,0,?,1,?,?) "
            "ON CONFLICT(bot_id) DO NOTHING",
            (bot_id, startapp_token, now, now),
        )
        _db.commit()
    state = dl_get(bot_id)
    assert state is not None
    return state


def dl_set_enabled(bot_id: int, enabled: bool) -> None:
    with _lock:
        _db.execute(
            "UPDATE direct_link_bots SET enabled=?, updated_at=? WHERE bot_id=?",
            (1 if enabled else 0, _now(), bot_id),
        )
        _db.commit()


def dl_rotate(bot_id: int, new_token: str) -> dict:
    with _lock:
        _db.execute(
            "UPDATE direct_link_bots SET startapp_token=?, "
            "token_version=token_version+1, updated_at=? WHERE bot_id=?",
            (new_token, _now(), bot_id),
        )
        _db.commit()
    state = dl_get(bot_id)
    assert state is not None
    return state
